s_num:1000
temperature noise :0.9486832980505138
temperature noise :0.9486832980505138
temperature noise :0.9486832980505138
obs_noise:0
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/shutil.py", line 806, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: './output_no.log' -> '../../output/final_result/amoc/scenario_amp3_new'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/amane/Downloads/research/sawada/thesis/tipping_points/predictability_tipping_lab/tipping_element/AMOC_tip_num_nonobs.py", line 250, in <module>
    shutil.move('./output_no.log',output)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/shutil.py", line 826, in move
    copy_function(src, real_dst)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '../../output/final_result/amoc/scenario_amp3_new'
